apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${MONGODB_NAME}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${MONGODB_NAME}
  labels:
    app: ${MONGODB_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${MONGODB_NAME}
  template:
    metadata:
      labels:
        app: ${MONGODB_NAME}
    spec:
      containers:
      - name: mongodb
        image: mongo:7.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: ${MONGODB_USERNAME}
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: ${MONGODB_PASSWORD}
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
        command: ["mongod"]
        args: ["--bind_ip_all", "--auth", "--port", "27017", "--dbpath", "/data/db"]
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: ${MONGODB_NAME}-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ${MONGODB_NAME}
spec:
  type: NodePort
  selector:
    app: ${MONGODB_NAME}
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
    nodePort: ${MONGODB_PORT}
