apiVersion: batch/v1
kind: Job
metadata:
  name: hms-init
spec:
  template:
    spec:
      containers:
        - name: hms-init
          image: apache/hive:3.1.3
          env:
            - name: SERVICE_NAME
              value: metastore
            - name: DB_DRIVER
              value: postgres
          command: ["/opt/hive/bin/schematool",  "-dbType", "postgres", "-initSchema"]
          volumeMounts:
            - mountPath: /opt/hive/lib/${POSTGRESQL_CONNECTOR_JAR_NAME}
              name: ${LIB_PV_NAME}
              subPath: ${POSTGRESQL_CONNECTOR_JAR_NAME}
            - mountPath: /opt/hive/lib/${JUICEFS_HADOOP_JAR_NAME}
              name: ${LIB_PV_NAME}
              subPath: ${JUICEFS_HADOOP_JAR_NAME}
            - mountPath: /opt/hive/conf/hive-site.xml
              name: hive-site-hms
              subPath: hive-site-hms.xml
            - mountPath: /opt/hive/conf/core-site.xml
              name: core-site
              subPath: core-site.xml
            - mountPath: /opt/hive/conf/hdfs-site.xml
              name: hdfs-site
              subPath: hdfs-site.xml
      volumes:
        - name: ${LIB_PV_NAME}
          persistentVolumeClaim:
            claimName: ${LIB_PVC_NAME}
        - name: core-site
          configMap:
            name: core-site
        - name: hive-site-hms
          configMap:
            name: hive-site-hms
        - name: hdfs-site
          configMap:
            name: hdfs-site
      restartPolicy: Never