apiVersion: batch/v1
kind: Job
metadata:
  name: hms-init
spec:
  template:
    spec:
      containers:
        - name: hms-init
          image: debian:${DEBIAN_IMAGE_VERSION}
          env:
            - name: JAVA_HOME
              value: ${CONTAINER_JAVA_HOME}
            - name: HADOOP_HOME
              value: ${CLIENT_DIR}/${HADOOP_CLIENT_DIR_NAME}
            - name: HIVE_HOME
              value: ${CLIENT_DIR}/${HIVE_CLIENT_DIR_NAME}
            - name: HIVE_CONF_DIR
              value: /etc/sqlrec/hms-conf
          command: ["${CLIENT_DIR}/${HIVE_CLIENT_DIR_NAME}/bin/schematool", "-dbType", "postgres", "-initSchema"]
          volumeMounts:
            - mountPath: ${CLIENT_DIR}
              name: client-pv
            - mountPath: ${CLIENT_DIR}/${HIVE_CLIENT_DIR_NAME}/lib/${POSTGRESQL_CONNECTOR_JAR_NAME}
              name: ${LIB_PV_NAME}
              subPath: ${POSTGRESQL_CONNECTOR_JAR_NAME}
            - mountPath: ${CLIENT_DIR}/${HIVE_CLIENT_DIR_NAME}/lib/${JUICEFS_HADOOP_JAR_NAME}
              name: ${LIB_PV_NAME}
              subPath: ${JUICEFS_HADOOP_JAR_NAME}
            - mountPath: /etc/sqlrec/hms-conf
              name: hms-conf
              readOnly: true
      volumes:
        - name: client-pv
          persistentVolumeClaim:
            claimName: ${CLIENT_PVC_NAME}
        - name: ${LIB_PV_NAME}
          persistentVolumeClaim:
            claimName: ${LIB_PVC_NAME}
        - name: hms-conf
          projected:
            sources:
              - configMap:
                  name: hive-site-hms
                  items:
                    - key: hive-site-hms.xml
                      path: hive-site.xml
              - configMap:
                  name: core-site
                  items:
                    - key: core-site.xml
                      path: core-site.xml
              - configMap:
                  name: hdfs-site
                  items:
                    - key: hdfs-site.xml
                      path: hdfs-site.xml
      restartPolicy: Never
