apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${LIB_PV_NAME}
spec:
  storageClassName: ""
  capacity:
    storage: ${LIB_STORAGE_SIZE}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: ${LIB_DIR}
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${LIB_PVC_NAME}
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${LIB_STORAGE_SIZE}
  volumeName: ${LIB_PV_NAME}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${CLIENT_PV_NAME}
spec:
  storageClassName: ""
  capacity:
    storage: ${CLIENT_STORAGE_SIZE}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: ${CLIENT_DIR}
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${CLIENT_PVC_NAME}
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${CLIENT_STORAGE_SIZE}
  volumeName: ${CLIENT_PV_NAME}
