apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyuubi
  labels:
    app: kyuubi
spec:
  replicas: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      app: kyuubi
  template:
    metadata:
      labels:
        app: kyuubi
    spec:
      serviceAccount: spark
      serviceAccountName: spark
      containers:
        - name: kyuubi
          image: debian:${DEBIAN_IMAGE_VERSION}
          env:
            - name: JAVA_HOME
              value: ${CONTAINER_JAVA_HOME}
            - name: KYUUBI_HOME
              value: ${CLIENT_DIR}/${KYUUBI_CLIENT_DIR_NAME}
            - name: SPARK_HOME
              value: ${CLIENT_DIR}/${SPARK_CLIENT_DIR_NAME}
            - name: HADOOP_CONF_DIR
              value: ${CLIENT_DIR}/${SPARK_CLIENT_DIR_NAME}/conf
          command:
            - ${CLIENT_DIR}/${KYUUBI_CLIENT_DIR_NAME}/bin/kyuubi
            - run
          ports:
            - containerPort: 10009
          startupProbe:
            tcpSocket:
              port: 10009
            periodSeconds: 2
            failureThreshold: 60
          readinessProbe:
            tcpSocket:
              port: 10009
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 10009
            periodSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - mountPath: ${CLIENT_DIR}
              name: client-pv
            - mountPath: ${CLIENT_DIR}/${KYUUBI_CLIENT_DIR_NAME}/logs
              name: kyuubi-logs
            - mountPath: ${CLIENT_DIR}/${KYUUBI_CLIENT_DIR_NAME}/pid
              name: kyuubi-pid
            - mountPath: ${CLIENT_DIR}/${KYUUBI_CLIENT_DIR_NAME}/work
              name: kyuubi-work
      volumes:
        - name: client-pv
          persistentVolumeClaim:
            claimName: ${CLIENT_PVC_NAME}
        - name: kyuubi-logs
          emptyDir: {}
        - name: kyuubi-pid
          emptyDir: {}
        - name: kyuubi-work
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kyuubi
spec:
  type: NodePort
  selector:
    app: kyuubi
  ports:
    - protocol: TCP
      port: 10009
      targetPort: 10009
      nodePort: ${KYUUBI_PORT}