apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${LIB_PV_NAME}
spec:
  storageClassName: ""
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: ${LIB_DIR}
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${LIB_PVC_NAME}
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeName: ${LIB_PV_NAME}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${CLIENT_PV_NAME}
spec:
  storageClassName: ""
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: ${CLIENT_DIR}
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${CLIENT_PVC_NAME}
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeName: ${CLIENT_PV_NAME}
