apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${LIB_PV_NAME}
spec:
  storageClassName: ""
  capacity:
    storage: 128Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: ${LIB_DIR}
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${LIB_PVC_NAME}
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi
  volumeName: ${LIB_PV_NAME}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${CLIENT_PV_NAME}
spec:
  storageClassName: ""
  capacity:
    storage: 128Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: ${CLIENT_DIR}
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${CLIENT_PVC_NAME}
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi
  volumeName: ${CLIENT_PV_NAME}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${HDFS_NAMENODE_PV_NAME}
spec:
  storageClassName: ""
  capacity:
    storage: 512Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: ${HDFS_NAMENODE_DATA_DIR}
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${HDFS_NAMENODE_PVC_NAME}
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Gi
  volumeName: ${HDFS_NAMENODE_PV_NAME}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${HDFS_DATANODE_PV_NAME}
spec:
  storageClassName: ""
  capacity:
    storage: 512Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: ${HDFS_DATANODE_DATA_DIR}
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${HDFS_DATANODE_PVC_NAME}
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Gi
  volumeName: ${HDFS_DATANODE_PV_NAME}
