apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${GROWTHBOOK_NAME}-uploads-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${GROWTHBOOK_NAME}
  labels:
    app: ${GROWTHBOOK_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${GROWTHBOOK_NAME}
  template:
    metadata:
      labels:
        app: ${GROWTHBOOK_NAME}
    spec:
      containers:
      - name: growthbook
        image: growthbook/growthbook:latest
        ports:
        - containerPort: 3000
        - containerPort: 3100
        env:
        - name: MONGODB_URI
          value: mongodb://${GROWTHBOOK_MONGODB_USER}:${GROWTHBOOK_MONGODB_PASSWORD}@${NODE_IP}:${GROWTHBOOK_MONGODB_PORT}/growthbook?authSource=admin
        volumeMounts:
        - name: uploads
          mountPath: /usr/local/src/app/packages/back-end/uploads
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: ${GROWTHBOOK_NAME}-uploads-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ${GROWTHBOOK_NAME}
spec:
  type: NodePort
  selector:
    app: ${GROWTHBOOK_NAME}
  ports:
  - name: web
    protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: ${GROWTHBOOK_WEB_PORT}
  - name: api
    protocol: TCP
    port: 3100
    targetPort: 3100
    nodePort: ${GROWTHBOOK_API_PORT}
