apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${HDFS_NAMENODE_PVC_NAME}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${HDFS_DATANODE_PVC_NAME}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Gi
