apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dolphinscheduler-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dolphinscheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dolphinscheduler
  template:
    metadata:
      labels:
        app: dolphinscheduler
    spec:
      serviceAccountName: spark
      containers:
      - name: dolphinscheduler-standalone-server
        image: apache/dolphinscheduler-standalone-server:${DOLPHINSCHEDULER_VERSION}
        ports:
        - containerPort: 12345
          name: api
        - containerPort: 25333
          name: python
        env:
        - name: DATABASE
          value: "postgresql"
        - name: SPRING_PROFILES_ACTIVE
          value: "postgresql"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://${NODE_IP}:${DOLPHINSCHEDULER_POSTGRESQL_PORT}/${DOLPHINSCHEDULER_DB}?sslmode=disable"
        - name: SPRING_DATASOURCE_USERNAME
          value: "${DOLPHINSCHEDULER_POSTGRESQL_USER}"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "${DOLPHINSCHEDULER_POSTGRESQL_PASSWORD}"
        - name: SPRING_JACKSON_TIME_ZONE
          value: "UTC"
        - name: HADOOP_HOME
          value: "${HADOOP_HOME}"
        - name: HIVE_HOME
          value: "${HIVE_HOME}"
        - name: SPARK_HOME
          value: "${SPARK_HOME}"
        - name: JAVA_HOME
          value: "${JAVA_HOME}"
        volumeMounts:
        - mountPath: ${CLIENT_DIR}
          name: client-dir
        - mountPath: /tmp/dolphinscheduler
          name: dolphinscheduler-data
      volumes:
      - name: client-dir
        persistentVolumeClaim:
          claimName: ${CLIENT_PVC_NAME}
      - name: dolphinscheduler-data
        persistentVolumeClaim:
          claimName: dolphinscheduler-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: dolphinscheduler
spec:
  type: NodePort
  selector:
    app: dolphinscheduler
  ports:
  - name: api
    port: 12345
    targetPort: 12345
    nodePort: ${DOLPHINSCHEDULER_PORT}
